### PR TITLE
Fix tests

### PR DESCRIPTION
**Pull request by imtayadeway**
I *think* this should fix the issue outlined in https://github.com/lbaillie/assemble/issues/2

There's a lot going on here, but I wanted to get this to green to help me figure out what was going on. LMK if you don't agree with everything, or if you want me to try to break this up into smaller chunks. May be best reviewed as individual commits.

Fixes https://github.com/lbaillie/assemble/issues/2

### CODE REVIEW

**Comment by lbaillie** [comment]
Awesome, thank you so much! I'm going to take a look at this over lunch today and I will get back at you with any comments or questions. You rock!

**Comment by imtayadeway** [comment]
@lbaillie since I had more time today I went back over my commits to provide a better explanation for what each revision was doing - hopefully that helps! But the above still applies - if you're unhappy with anything, or if it's too big to review, will happily work with you to get the stuff you want in there.

**Comment by imtayadeway** [comment]
@lbaillie I pulled the important bits out of this PR into #3. Probably best that I rebase this after that is merged (if that works out), and I will QA this with the front-end app. There are some potentially breaking changes in this PR, so I really should make sure :smile: 

> The first is that I actually don't want there to be any connection between uses and alerts in the DB

In the meantime, I took care of this in https://github.com/lbaillie/assemble-api/pull/2/commits/449697ba604060ad53598113594738da42d34cad

**Comment by lbaillie** [comment]
The other two PRs look good to me, and in QAing them together they do fix the issue, so I'm gonna merge those two now. Feel free to continue work on this one by rebasing and just making sure nothing breaks :stuck_out_tongue: Thanks again for all your help!

**Comment by imtayadeway** [comment]
@lbaillie updated so the only possible breaking change is [here](https://github.com/lbaillie/assemble-api/pull/2/files#diff-4676c008b11a5480d73d4a6de01e45b9L8), but I'm pretty sure that you indicated this was how it was supposed to be.

Think I had let some things creep into this PR that were more like refactorings/opinions that might best belong in another PR and also require conversations about them. Which I am happy to do, just let me know! This now represents what I think is the bare minimum to get all the current tests to pass. Hope this helps!

**Comment by lbaillie** [comment]
I'm actually fine with everything as it is in this PR (thanks again!), but I just added Travis to the repo today (and just updated it so it actually runs properly) so would you mind rebasing again? I ran the tests locally and they all passed, so I'm sure that's the only reason why this PR is currently failing.

**Comment by imtayadeway** [comment]
:green_apple: :green_heart: :green_book: yay!

**Pull request merged**
